// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Database.Context;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(SaraDbContext))]
    [Migration("20260427085348_RefactorWorkflowSteps")]
    partial class RefactorWorkflowSteps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Database.Models.AnalysisMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysesToBeRun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InspectionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tag", "InspectionDescription")
                        .IsUnique();

                    b.ToTable("AnalysisMapping");
                });

            modelBuilder.Entity("api.Database.Models.AnonymizationData", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsPersonInImage")
                        .HasColumnType("boolean");

                    b.HasKey("WorkflowStepId");

                    b.ToTable("AnonymizationData");
                });

            modelBuilder.Entity("api.Database.Models.CLOEData", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<float?>("OilLevel")
                        .HasColumnType("real");

                    b.HasKey("WorkflowStepId");

                    b.ToTable("CLOEData");
                });

            modelBuilder.Entity("api.Database.Models.FencillaData", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<bool?>("IsBreak")
                        .HasColumnType("boolean");

                    b.HasKey("WorkflowStepId");

                    b.ToTable("FencillaData");
                });

            modelBuilder.Entity("api.Database.Models.PlantData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionDescription")
                        .HasColumnType("text");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RobotName")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.HasIndex("DateCreated", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_PlantData_DateCreated_Id_Desc");

                    b.ToTable("PlantData");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReadingData", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("WorkflowStepId");

                    b.ToTable("ThermalReadingData");
                });

            modelBuilder.Entity("api.Database.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("api.Database.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Type")
                        .IsUnique();

                    b.ToTable("WorkflowStep");
                });

            modelBuilder.Entity("api.Database.Models.AnonymizationData", b =>
                {
                    b.HasOne("api.Database.Models.WorkflowStep", "WorkflowStep")
                        .WithOne("AnonymizationData")
                        .HasForeignKey("api.Database.Models.AnonymizationData", "WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "PreProcessedBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("AnonymizationDataWorkflowStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnonymizationDataWorkflowStepId");

                            b1.ToTable("AnonymizationData");

                            b1.WithOwner()
                                .HasForeignKey("AnonymizationDataWorkflowStepId");
                        });

                    b.Navigation("PreProcessedBlobStorageLocation");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("api.Database.Models.CLOEData", b =>
                {
                    b.HasOne("api.Database.Models.WorkflowStep", "WorkflowStep")
                        .WithOne("CLOEData")
                        .HasForeignKey("api.Database.Models.CLOEData", "WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("api.Database.Models.FencillaData", b =>
                {
                    b.HasOne("api.Database.Models.WorkflowStep", "WorkflowStep")
                        .WithOne("FencillaData")
                        .HasForeignKey("api.Database.Models.FencillaData", "WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("api.Database.Models.PlantData", b =>
                {
                    b.HasOne("api.Database.Models.Workflow", "Workflow")
                        .WithOne()
                        .HasForeignKey("api.Database.Models.PlantData", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReadingData", b =>
                {
                    b.HasOne("api.Database.Models.WorkflowStep", "WorkflowStep")
                        .WithOne("ThermalReadingData")
                        .HasForeignKey("api.Database.Models.ThermalReadingData", "WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("api.Database.Models.WorkflowStep", b =>
                {
                    b.HasOne("api.Database.Models.Workflow", "Workflow")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "DestinationBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("WorkflowStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowStepId");

                            b1.ToTable("WorkflowStep");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowStepId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "SourceBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("WorkflowStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowStepId");

                            b1.ToTable("WorkflowStep");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowStepId");
                        });

                    b.Navigation("DestinationBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("SourceBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api.Database.Models.Workflow", b =>
                {
                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("api.Database.Models.WorkflowStep", b =>
                {
                    b.Navigation("AnonymizationData");

                    b.Navigation("CLOEData");

                    b.Navigation("FencillaData");

                    b.Navigation("ThermalReadingData");
                });
#pragma warning restore 612, 618
        }
    }
}
